version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface
    volumes:
      - ./data/raw:/data:ro
      - ./init:/docker-entrypoint-initdb.d
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_user_files:/var/lib/clickhouse/user_files

    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password

volumes:
  clickhouse_data:
  clickhouse_user_files:
