baseURL = 'https://mxmueller.github.io/optimizing-pairs-trading/'
languageCode = 'en-us'
title = 'Exploring Machine Learning Optimizatios for Pair Selection in Pairs Trading'
theme = 'typo'
canonifyURLs = true

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false



# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

homeIntroTitle = 'About'
homeIntroContent = """
This research project explores **Machine Learning Optimizations for Pair Selection in Pairs Trading**, investigating whether modern ML approaches can outperform traditional statistical methods in identifying profitable trading pairs. The study compares machine learning techniques (Gradient Boost Regressor and Affinity Propagation) against conventional cointegration-based methods, testing their performance on major European and US indices.

This work is conducted as a **two-semester student research project** at the [DHBW Heidenheim](https://www.heidenheim.dhbw.de/en/home), focusing on the intersection of quantitative finance and machine learning applications in algorithmic trading.

****

**Author:** Maximilian Müller  
[LinkedIn](https://www.linkedin.com/in/maximilian-m%C3%BCller-485295209/) | [GitHub](https://github.com/mxmueller)

**Supervisor:** [Prof. Dr. Anke Hutzschenreuter](https://www.heidenheim.dhbw.de/dhbw-heidenheim/ansprechpersonen/prof-dr-anke-hutzschenreuter)  
Cooperative State University Heidenheim

"""

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = false
home = "About"


[[params.social]]
name = "github"
url = "https://github.com/mxmueller/optimizing-pairs-trading"

# Main menu pages
[[params.menu]]
name = "Docs"
url = "/docs/"

[[params.menu]]
name = "Results" 
url = "/results/"

[[params.menu]]
name = "Setup"
url = "/setup/"

[[params.menu]]
name = "Backtester"
url = "/backtester/"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true
